import type { Metadata } from "next";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.scss";

import localFont from "next/font/local";

const pixerFont = localFont({ src: "./fonts/clacon2.woff2" });

export const metadata: Metadata = {
  title: "kAIa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-lm-black text-white ${pixerFont.className}`}
      >
        <div className="scanlines"></div>
        <div className="flex h-dvh w-dvw flex-col">{children}</div>
      </body>
    </html>
  );
}
